// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpablrwoifhggvthkzoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwYWJscndvaWZoZ2d2dGhrem9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjM4NTUsImV4cCI6MjA2MzkzOTg1NX0.z7033xjmmeRxJ-O7NjE91nU2SgYMEtTsJyQLcenTKFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);